services:
  nacos: #服务名随便起
    image: nacos/nacos-server:v2.2.1 #拉取得镜像对应得版本号
    container_name: nacos   #启动后容器名
    environment:
      - MODE=standalone    
    env_file:
      - ./conf/nacos-config.env  #环境配置文件
    volumes: #挂载 本地路径:容器路径
      - ./logs:/home/nacos/logs 
      - ./init.d:/home/nacos/init.d
      - ./data:/home/nacos/data
      - ./nacos-conf:/home/nacos/conf
    ports: #暴露端口
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
      - "9849:9849"
    restart: unless-stopped 
    networks:
      - dockernetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/"]
      interval: 30s
      timeout: 10s
      retries: 3      

networks:
  dockernetwork:
    driver: bridge
    external: true
