server:
  port: 7091

spring:
  application:
    name: seata-server

logging:
  config: classpath:logback-spring.xml
  file:
    path: ${user.home}/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: seata
seata:
  config:
    type: nacos
    nacos:
      server-addr: nacos:8848   # nacos的访问地址，因为是在docker中，ip地址改为宿主机地址
      namespace: 969f5576-5dcf-49f8-97c3-2dc5057c1b91
      group: DEFAULT_GROUP  # nacos的分组
      username: nacos     # nacos的用户名
      password: nacos     # nacos的密码
      context-path:
      data-id: seata-server.properties  # nacos中的配置文件名称
  registry:
    type: nacos
    nacos:
      application: seata-server       # seata启动后在nacos的服务名
      server-addr: nacos:8848  # nacos的访问地址，因为是在docker中，ip地址改为宿主机地址
      group: DEFAULT_GROUP   # nacos的分组
      namespace: 969f5576-5dcf-49f8-97c3-2dc5057c1b91
      cluster: datasource     # 这个歌参数在每个微服务seata时会用到
      username: nacos      # nacos的用户名
      password: nacos      # nacos的密码
      context-path:

  # store:
    # support: file 、 db 、 redis
    mode: file
#  server:
#    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.jpeg,/**/*.ico,/api/v1/auth/login